FORMAT: 1A
HOST: https://accounts.pdk.io/api/v1

# PDK Auth API
The PDK Auth API is a collection of centralized authentication and authorization endpoints for initiating and managing secure interaction with the suite of PDK APIs.
